# 使用官方的 Python 基础镜像
FROM ghcr.io/asyncfuncai/deepwiki-open:sha-bb3c67d

# 设置工作目录
WORKDIR /app

RUN rm -rf /app/api
RUN rm -rf /app/package.json
RUN rm -rf /app/.next


COPY api ./api
COPY package.json ./package.json
COPY .next ./.next
COPY cl100k_base.tiktoken ./cl100k_base.tiktoken
RUN sed -i 's|https://openaipublic.blob.core.windows.net/encodings/cl100k_base.tiktoken|/app/cl100k_base.tiktoken|g' /opt/venv/lib/python3.11/site-packages/tiktoken_ext/openai_public.py
# Set environment variables
ENV PORT=8001
ENV NODE_ENV=production
ENV SERVER_BASE_URL=http://localhost:${PORT:-8001}


# Command to run the application
CMD ["/app/start.sh"]





